<?php

/**
 * @file
 * Contains custom_info.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function custom_info_help($route_name) {
  if ($route_name == 'help.page.custom_info') {
    // Main module help for the custom_info module.
    $output = '';
    $output .= '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t("This module modifies Drupal's Site Information.") . '</p>';

  }
  return $output;
}

/**
 * Implements hook_form_alter().
 */
function custom_info_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Get the right config file for Site Configuration.
  $configFactory = \Drupal::configFactory();
  $siteConfig = $configFactory->get('system.site');
  // Check for the correct form.
  if ($form_id == 'system_site_information_settings') {
    // Add new form textfield.
    $form['siteapikey'] = [
      '#type' => 'textfield',
      '#title' => t('Site API Key'),
      '#maxlength' => '60',
      '#attributes' => ['placeholder' => t('Type your API KEY')],
      '#default_value' => $siteConfig->get('siteapikey') != "" ? $siteConfig->get('siteapikey') : t('No API Key yet'),
    ];
    // Change save button text.
    $form['actions']['submit']['#value'] = t('Update Configuration');
    // Custom submit to save new value.
    $form['#submit'][] = 'site_information_form_submit';
  }
}

/**
 * Function to save siteapikey.
 */
function site_information_form_submit(&$form, &$form_state) {
  // Get the right config file for Site Configuration.
  $configFactory = \Drupal::configFactory();
  $siteConfig = $configFactory->get('system.site');

  if (isset($siteConfig)) {
    // Add 'siteapikey' in 'system.site' configuration.
    $config = $configFactory->getEditable('system.site');
    $config->set('siteapikey', $form_state->getValue('siteapikey'));
    $config->save(TRUE);
  }
  drupal_set_message(t('Site API key set to:') . ' ' . $form_state->getValue('siteapikey'));
}
